/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;
using BankTechAPI.Standard.Http.Request;
using BankTechAPI.Standard.Http.Response;
using BankTechAPI.Standard.Http.Client;
using BankTechAPI.Standard.Exceptions;

namespace BankTechAPI.Standard.Controllers
{
    public partial class TransactController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static TransactController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static TransactController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new TransactController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="collectionIdentification">Required parameter: (Required) The parameters.</param>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <return>Returns the Models.CollectionReturned response from the API call</return>
        public Models.CollectionReturned GetACollectionMatchingTheProvidedParameters(string collectionIdentification, double xApiVersion)
        {
            Task<Models.CollectionReturned> t = GetACollectionMatchingTheProvidedParametersAsync(collectionIdentification, xApiVersion);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="collectionIdentification">Required parameter: (Required) The parameters.</param>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <return>Returns the Models.CollectionReturned response from the API call</return>
        public async Task<Models.CollectionReturned> GetACollectionMatchingTheProvidedParametersAsync(string collectionIdentification, double xApiVersion)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/Transact/collection/{collectionIdentification}");

            //process optional template parameters
            APIHelper.AppendUrlWithTemplateParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "collectionIdentification", collectionIdentification }
            });


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "x-api-version", xApiVersion.ToString() }
            };
            _headers.Add("x-api-version", Configuration.XApiVersion);
            _headers.Add("x-api-key", Configuration.XApiKey);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new BadRequestException(@"Bad Request", _context);

            if (_response.StatusCode == 401)
                throw new UnauthorizedRequestException(@"Unauthorized", _context);

            if (_response.StatusCode == 403)
                throw new ForbiddenRequestException(@"Forbidden", _context);

            if (_response.StatusCode == 404)
                throw new CollectionNotFoundException(@"Not Found", _context);

            if (_response.StatusCode == 500)
                throw new AnUnexpectedErrorHasOccuredPleaseContactYourAdministratorException(@"Internal Server Error", _context);

            if (_response.StatusCode == 503)
                throw new ServiceIsCurrentlyUnavailablePleaseTryAgainLaterOrContactYourAdministratorException(@"Service Unavailable", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.CollectionReturned>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CollectionSCreated1 response from the API call</return>
        public Models.CollectionSCreated1 CreateNewEFTCollectionS(double xApiVersion, string contentType, List<Models.CreateNewEFTCollectionSRequest> body)
        {
            Task<Models.CollectionSCreated1> t = CreateNewEFTCollectionSAsync(xApiVersion, contentType, body);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CollectionSCreated1 response from the API call</return>
        public async Task<Models.CollectionSCreated1> CreateNewEFTCollectionSAsync(double xApiVersion, string contentType, List<Models.CreateNewEFTCollectionSRequest> body)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/Transact/eftcollect");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "x-api-version", xApiVersion.ToString() },
                { "Content-Type", contentType }
            };
            _headers.Add("x-api-version", Configuration.XApiVersion);
            _headers.Add("x-api-key", Configuration.XApiKey);

            //append body params
            var _body = APIHelper.JsonSerialize(body);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.PostBody(_queryUrl, _headers, _body);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new BadRequestException(@"Bad Request", _context);

            if (_response.StatusCode == 401)
                throw new UnauthorizedRequestException(@"Unauthorized", _context);

            if (_response.StatusCode == 403)
                throw new ForbiddenRequestException(@"Forbidden", _context);

            if (_response.StatusCode == 404)
                throw new MandateNotFoundException(@"Not Found", _context);

            if (_response.StatusCode == 500)
                throw new AnUnexpectedErrorHasOccuredPleaseContactYourAdministratorException(@"Internal Server Error", _context);

            if (_response.StatusCode == 503)
                throw new ServiceIsCurrentlyUnavailablePleaseTryAgainLaterOrContactYourAdministratorException(@"Service Unavailable", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.CollectionSCreated1>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CollectionSCreated1 response from the API call</return>
        public Models.CollectionSCreated1 CreateNewNaedoCollectionS(double xApiVersion, string contentType, List<Models.CreateNewNaedoCollectionSRequest> body)
        {
            Task<Models.CollectionSCreated1> t = CreateNewNaedoCollectionSAsync(xApiVersion, contentType, body);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CollectionSCreated1 response from the API call</return>
        public async Task<Models.CollectionSCreated1> CreateNewNaedoCollectionSAsync(double xApiVersion, string contentType, List<Models.CreateNewNaedoCollectionSRequest> body)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/Transact/naedocollect");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "x-api-version", xApiVersion.ToString() },
                { "Content-Type", contentType }
            };
            _headers.Add("x-api-version", Configuration.XApiVersion);
            _headers.Add("x-api-key", Configuration.XApiKey);

            //append body params
            var _body = APIHelper.JsonSerialize(body);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.PostBody(_queryUrl, _headers, _body);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new BadRequestException(@"Bad Request", _context);

            if (_response.StatusCode == 401)
                throw new UnauthorizedRequestException(@"Unauthorized", _context);

            if (_response.StatusCode == 403)
                throw new ForbiddenRequestException(@"Forbidden", _context);

            if (_response.StatusCode == 404)
                throw new MandateNotFoundException(@"Not Found", _context);

            if (_response.StatusCode == 500)
                throw new AnUnexpectedErrorHasOccuredPleaseContactYourAdministratorException(@"Internal Server Error", _context);

            if (_response.StatusCode == 503)
                throw new ServiceIsCurrentlyUnavailablePleaseTryAgainLaterOrContactYourAdministratorException(@"Service Unavailable", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.CollectionSCreated1>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CollectionSCreated1 response from the API call</return>
        public Models.CollectionSCreated1 CreateNewDebiCheckCollectionS(double xApiVersion, string contentType, List<Models.CreateNewDebiCheckCollectionSRequest> body)
        {
            Task<Models.CollectionSCreated1> t = CreateNewDebiCheckCollectionSAsync(xApiVersion, contentType, body);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CollectionSCreated1 response from the API call</return>
        public async Task<Models.CollectionSCreated1> CreateNewDebiCheckCollectionSAsync(double xApiVersion, string contentType, List<Models.CreateNewDebiCheckCollectionSRequest> body)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/Transact/debicheckcollect");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "x-api-version", xApiVersion.ToString() },
                { "Content-Type", contentType }
            };
            _headers.Add("x-api-version", Configuration.XApiVersion);
            _headers.Add("x-api-key", Configuration.XApiKey);

            //append body params
            var _body = APIHelper.JsonSerialize(body);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.PostBody(_queryUrl, _headers, _body);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new BadRequestException(@"Bad Request", _context);

            if (_response.StatusCode == 401)
                throw new UnauthorizedRequestException(@"Unauthorized", _context);

            if (_response.StatusCode == 403)
                throw new ForbiddenRequestException(@"Forbidden", _context);

            if (_response.StatusCode == 404)
                throw new MandateNotFoundException(@"Not Found", _context);

            if (_response.StatusCode == 500)
                throw new AnUnexpectedErrorHasOccuredPleaseContactYourAdministratorException(@"Internal Server Error", _context);

            if (_response.StatusCode == 503)
                throw new ServiceIsCurrentlyUnavailablePleaseTryAgainLaterOrContactYourAdministratorException(@"Service Unavailable", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.CollectionSCreated1>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CollectionSCreated1 response from the API call</return>
        public Models.CollectionSCreated1 CreateRecallCreatedCollectionS(double xApiVersion, string contentType, List<Models.RecallCreatedCollectionSRequest> body)
        {
            Task<Models.CollectionSCreated1> t = CreateRecallCreatedCollectionSAsync(xApiVersion, contentType, body);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.CollectionSCreated1 response from the API call</return>
        public async Task<Models.CollectionSCreated1> CreateRecallCreatedCollectionSAsync(double xApiVersion, string contentType, List<Models.RecallCreatedCollectionSRequest> body)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/Transact/recallcollection");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "x-api-version", xApiVersion.ToString() },
                { "Content-Type", contentType }
            };
            _headers.Add("x-api-version", Configuration.XApiVersion);
            _headers.Add("x-api-key", Configuration.XApiKey);

            //append body params
            var _body = APIHelper.JsonSerialize(body);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.PostBody(_queryUrl, _headers, _body);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new BadRequestException(@"Bad Request", _context);

            if (_response.StatusCode == 401)
                throw new UnauthorizedRequestException(@"Unauthorized", _context);

            if (_response.StatusCode == 403)
                throw new ForbiddenRequestException(@"Forbidden", _context);

            if (_response.StatusCode == 404)
                throw new MandateNotFoundException(@"Not Found", _context);

            if (_response.StatusCode == 500)
                throw new AnUnexpectedErrorHasOccuredPleaseContactYourAdministratorException(@"Internal Server Error", _context);

            if (_response.StatusCode == 503)
                throw new ServiceIsCurrentlyUnavailablePleaseTryAgainLaterOrContactYourAdministratorException(@"Service Unavailable", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.CollectionSCreated1>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.PaymentSCreated response from the API call</return>
        public Models.PaymentSCreated CreateNewPaymentS(double xApiVersion, string contentType, List<Models.CreateNewPaymentSRequest> body)
        {
            Task<Models.PaymentSCreated> t = CreateNewPaymentSAsync(xApiVersion, contentType, body);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// TODO: type endpoint description here
        /// </summary>
        /// <param name="xApiVersion">Required parameter: The requested API version</param>
        /// <param name="contentType">Required parameter: Example: </param>
        /// <param name="body">Required parameter: Example: </param>
        /// <return>Returns the Models.PaymentSCreated response from the API call</return>
        public async Task<Models.PaymentSCreated> CreateNewPaymentSAsync(double xApiVersion, string contentType, List<Models.CreateNewPaymentSRequest> body)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/Transact/paymentcreate");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" },
                { "x-api-version", xApiVersion.ToString() },
                { "Content-Type", contentType }
            };
            _headers.Add("x-api-version", Configuration.XApiVersion);
            _headers.Add("x-api-key", Configuration.XApiKey);

            //append body params
            var _body = APIHelper.JsonSerialize(body);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.PostBody(_queryUrl, _headers, _body);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new BadRequestException(@"Bad Request", _context);

            if (_response.StatusCode == 401)
                throw new UnauthorizedRequestException(@"Unauthorized", _context);

            if (_response.StatusCode == 403)
                throw new ForbiddenRequestException(@"Forbidden", _context);

            if (_response.StatusCode == 404)
                throw new NotFoundException(@"Not Found", _context);

            if (_response.StatusCode == 500)
                throw new AnUnexpectedErrorHasOccuredPleaseContactYourAdministratorException(@"Internal Server Error", _context);

            if (_response.StatusCode == 503)
                throw new ServiceIsCurrentlyUnavailablePleaseTryAgainLaterOrContactYourAdministratorException(@"Service Unavailable", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.PaymentSCreated>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 