/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using BankTechAPI.Standard.Controllers;
using BankTechAPI.Standard.Http.Client;
using BankTechAPI.Standard.Utilities;

namespace BankTechAPI.Standard
{
    public partial class BankTechAPIClient
    {

        /// <summary>
        /// Singleton access to Communication controller
        /// </summary>
        public CommunicationController Communication
        {
            get
            {
                return CommunicationController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Mandate controller
        /// </summary>
        public MandateController Mandate
        {
            get
            {
                return MandateController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Service controller
        /// </summary>
        public ServiceController Service
        {
            get
            {
                return ServiceController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Transact controller
        /// </summary>
        public TransactController Transact
        {
            get
            {
                return TransactController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Verify controller
        /// </summary>
        public VerifyController Verify
        {
            get
            {
                return VerifyController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public BankTechAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public BankTechAPIClient(string xApiVersion, string xApiKey)
        {
            Configuration.XApiVersion = xApiVersion;
            Configuration.XApiKey = xApiKey;
        }
        #endregion
    }
}