/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class ABSABankAccountVerificationReportRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string bank;
        private string branchCode;
        private string accountNumber;
        private string accountType;
        private string idType;
        private string idNumber;
        private string surname;
        private string initials;
        private string emailAddress;
        private string phoneNumber;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bank")]
        public string Bank 
        { 
            get 
            {
                return this.bank; 
            } 
            set 
            {
                this.bank = value;
                onPropertyChanged("Bank");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("branchCode")]
        public string BranchCode 
        { 
            get 
            {
                return this.branchCode; 
            } 
            set 
            {
                this.branchCode = value;
                onPropertyChanged("BranchCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountNumber")]
        public string AccountNumber 
        { 
            get 
            {
                return this.accountNumber; 
            } 
            set 
            {
                this.accountNumber = value;
                onPropertyChanged("AccountNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountType")]
        public string AccountType 
        { 
            get 
            {
                return this.accountType; 
            } 
            set 
            {
                this.accountType = value;
                onPropertyChanged("AccountType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("idType")]
        public string IdType 
        { 
            get 
            {
                return this.idType; 
            } 
            set 
            {
                this.idType = value;
                onPropertyChanged("IdType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("idNumber")]
        public string IdNumber 
        { 
            get 
            {
                return this.idNumber; 
            } 
            set 
            {
                this.idNumber = value;
                onPropertyChanged("IdNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("surname")]
        public string Surname 
        { 
            get 
            {
                return this.surname; 
            } 
            set 
            {
                this.surname = value;
                onPropertyChanged("Surname");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("initials")]
        public string Initials 
        { 
            get 
            {
                return this.initials; 
            } 
            set 
            {
                this.initials = value;
                onPropertyChanged("Initials");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("emailAddress")]
        public string EmailAddress 
        { 
            get 
            {
                return this.emailAddress; 
            } 
            set 
            {
                this.emailAddress = value;
                onPropertyChanged("EmailAddress");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string PhoneNumber 
        { 
            get 
            {
                return this.phoneNumber; 
            } 
            set 
            {
                this.phoneNumber = value;
                onPropertyChanged("PhoneNumber");
            }
        }
    }
} 