/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class AdditionalDatum : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string fieldName;
        private string mvalue;
        private string dataType;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fieldName")]
        public string FieldName 
        { 
            get 
            {
                return this.fieldName; 
            } 
            set 
            {
                this.fieldName = value;
                onPropertyChanged("FieldName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("value")]
        public string Value 
        { 
            get 
            {
                return this.mvalue; 
            } 
            set 
            {
                this.mvalue = value;
                onPropertyChanged("Value");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("dataType")]
        public string DataType 
        { 
            get 
            {
                return this.dataType; 
            } 
            set 
            {
                this.dataType = value;
                onPropertyChanged("DataType");
            }
        }
    }
} 