/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class BusinessInformation : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string displayText;
        private string commercialName;
        private string registrationNo;
        private string businessStartDate;
        private string financialYearEnd;
        private string registrationNoOld;
        private string commercialStatus;
        private string commercialType;
        private string sic;
        private string taxNo;
        private string referenceNo;
        private string externalReference;
        private string tradeName;
        private string previousBussName;
        private string physicalAddress;
        private string postalAddress;
        private string registrationDate;
        private string businessDesc;
        private string telephoneNo;
        private string faxNo;
        private string bussEmail;
        private string bussWebsite;
        private string noOfEnquiries;
        private string nameChangeDate;
        private string ageofBusiness;
        private string authorisedCapitalAmt;
        private string issuedNoOfShares;
        private string registrationNoConverted;
        private string financialEffectiveDate;
        private string authorisedNoOfShares;
        private string issuedCapitalAmt;
        private string commercialStatusDate;
        private string directorCount;
        private string vatNo;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("displayText")]
        public string DisplayText 
        { 
            get 
            {
                return this.displayText; 
            } 
            set 
            {
                this.displayText = value;
                onPropertyChanged("DisplayText");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("commercialName")]
        public string CommercialName 
        { 
            get 
            {
                return this.commercialName; 
            } 
            set 
            {
                this.commercialName = value;
                onPropertyChanged("CommercialName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("registrationNo")]
        public string RegistrationNo 
        { 
            get 
            {
                return this.registrationNo; 
            } 
            set 
            {
                this.registrationNo = value;
                onPropertyChanged("RegistrationNo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("businessStartDate")]
        public string BusinessStartDate 
        { 
            get 
            {
                return this.businessStartDate; 
            } 
            set 
            {
                this.businessStartDate = value;
                onPropertyChanged("BusinessStartDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("financialYearEnd")]
        public string FinancialYearEnd 
        { 
            get 
            {
                return this.financialYearEnd; 
            } 
            set 
            {
                this.financialYearEnd = value;
                onPropertyChanged("FinancialYearEnd");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("registrationNoOld")]
        public string RegistrationNoOld 
        { 
            get 
            {
                return this.registrationNoOld; 
            } 
            set 
            {
                this.registrationNoOld = value;
                onPropertyChanged("RegistrationNoOld");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("commercialStatus")]
        public string CommercialStatus 
        { 
            get 
            {
                return this.commercialStatus; 
            } 
            set 
            {
                this.commercialStatus = value;
                onPropertyChanged("CommercialStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("commercialType")]
        public string CommercialType 
        { 
            get 
            {
                return this.commercialType; 
            } 
            set 
            {
                this.commercialType = value;
                onPropertyChanged("CommercialType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sic")]
        public string Sic 
        { 
            get 
            {
                return this.sic; 
            } 
            set 
            {
                this.sic = value;
                onPropertyChanged("Sic");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("taxNo")]
        public string TaxNo 
        { 
            get 
            {
                return this.taxNo; 
            } 
            set 
            {
                this.taxNo = value;
                onPropertyChanged("TaxNo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("referenceNo")]
        public string ReferenceNo 
        { 
            get 
            {
                return this.referenceNo; 
            } 
            set 
            {
                this.referenceNo = value;
                onPropertyChanged("ReferenceNo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("externalReference")]
        public string ExternalReference 
        { 
            get 
            {
                return this.externalReference; 
            } 
            set 
            {
                this.externalReference = value;
                onPropertyChanged("ExternalReference");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("tradeName")]
        public string TradeName 
        { 
            get 
            {
                return this.tradeName; 
            } 
            set 
            {
                this.tradeName = value;
                onPropertyChanged("TradeName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("previousBussName")]
        public string PreviousBussName 
        { 
            get 
            {
                return this.previousBussName; 
            } 
            set 
            {
                this.previousBussName = value;
                onPropertyChanged("PreviousBussName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("physicalAddress")]
        public string PhysicalAddress 
        { 
            get 
            {
                return this.physicalAddress; 
            } 
            set 
            {
                this.physicalAddress = value;
                onPropertyChanged("PhysicalAddress");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postalAddress")]
        public string PostalAddress 
        { 
            get 
            {
                return this.postalAddress; 
            } 
            set 
            {
                this.postalAddress = value;
                onPropertyChanged("PostalAddress");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("registrationDate")]
        public string RegistrationDate 
        { 
            get 
            {
                return this.registrationDate; 
            } 
            set 
            {
                this.registrationDate = value;
                onPropertyChanged("RegistrationDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("businessDesc")]
        public string BusinessDesc 
        { 
            get 
            {
                return this.businessDesc; 
            } 
            set 
            {
                this.businessDesc = value;
                onPropertyChanged("BusinessDesc");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("telephoneNo")]
        public string TelephoneNo 
        { 
            get 
            {
                return this.telephoneNo; 
            } 
            set 
            {
                this.telephoneNo = value;
                onPropertyChanged("TelephoneNo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("faxNo")]
        public string FaxNo 
        { 
            get 
            {
                return this.faxNo; 
            } 
            set 
            {
                this.faxNo = value;
                onPropertyChanged("FaxNo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bussEmail")]
        public string BussEmail 
        { 
            get 
            {
                return this.bussEmail; 
            } 
            set 
            {
                this.bussEmail = value;
                onPropertyChanged("BussEmail");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bussWebsite")]
        public string BussWebsite 
        { 
            get 
            {
                return this.bussWebsite; 
            } 
            set 
            {
                this.bussWebsite = value;
                onPropertyChanged("BussWebsite");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("noOfEnquiries")]
        public string NoOfEnquiries 
        { 
            get 
            {
                return this.noOfEnquiries; 
            } 
            set 
            {
                this.noOfEnquiries = value;
                onPropertyChanged("NoOfEnquiries");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nameChangeDate")]
        public string NameChangeDate 
        { 
            get 
            {
                return this.nameChangeDate; 
            } 
            set 
            {
                this.nameChangeDate = value;
                onPropertyChanged("NameChangeDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ageofBusiness")]
        public string AgeofBusiness 
        { 
            get 
            {
                return this.ageofBusiness; 
            } 
            set 
            {
                this.ageofBusiness = value;
                onPropertyChanged("AgeofBusiness");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("authorisedCapitalAmt")]
        public string AuthorisedCapitalAmt 
        { 
            get 
            {
                return this.authorisedCapitalAmt; 
            } 
            set 
            {
                this.authorisedCapitalAmt = value;
                onPropertyChanged("AuthorisedCapitalAmt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("issuedNoOfShares")]
        public string IssuedNoOfShares 
        { 
            get 
            {
                return this.issuedNoOfShares; 
            } 
            set 
            {
                this.issuedNoOfShares = value;
                onPropertyChanged("IssuedNoOfShares");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("registrationNoConverted")]
        public string RegistrationNoConverted 
        { 
            get 
            {
                return this.registrationNoConverted; 
            } 
            set 
            {
                this.registrationNoConverted = value;
                onPropertyChanged("RegistrationNoConverted");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("financialEffectiveDate")]
        public string FinancialEffectiveDate 
        { 
            get 
            {
                return this.financialEffectiveDate; 
            } 
            set 
            {
                this.financialEffectiveDate = value;
                onPropertyChanged("FinancialEffectiveDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("authorisedNoOfShares")]
        public string AuthorisedNoOfShares 
        { 
            get 
            {
                return this.authorisedNoOfShares; 
            } 
            set 
            {
                this.authorisedNoOfShares = value;
                onPropertyChanged("AuthorisedNoOfShares");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("issuedCapitalAmt")]
        public string IssuedCapitalAmt 
        { 
            get 
            {
                return this.issuedCapitalAmt; 
            } 
            set 
            {
                this.issuedCapitalAmt = value;
                onPropertyChanged("IssuedCapitalAmt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("commercialStatusDate")]
        public string CommercialStatusDate 
        { 
            get 
            {
                return this.commercialStatusDate; 
            } 
            set 
            {
                this.commercialStatusDate = value;
                onPropertyChanged("CommercialStatusDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("directorCount")]
        public string DirectorCount 
        { 
            get 
            {
                return this.directorCount; 
            } 
            set 
            {
                this.directorCount = value;
                onPropertyChanged("DirectorCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("vatNo")]
        public string VatNo 
        { 
            get 
            {
                return this.vatNo; 
            } 
            set 
            {
                this.vatNo = value;
                onPropertyChanged("VatNo");
            }
        }
    }
} 