/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class Contract : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string contractNo;
        private string contractStatus;
        private string statusDate;
        private string contractStartDate;
        private string contractEndDate;
        private string salesTeam;
        private string salesPerson;
        private Models.Customer customer;
        private Models.Product product;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contractNo")]
        public string ContractNo 
        { 
            get 
            {
                return this.contractNo; 
            } 
            set 
            {
                this.contractNo = value;
                onPropertyChanged("ContractNo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contractStatus")]
        public string ContractStatus 
        { 
            get 
            {
                return this.contractStatus; 
            } 
            set 
            {
                this.contractStatus = value;
                onPropertyChanged("ContractStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("statusDate")]
        public string StatusDate 
        { 
            get 
            {
                return this.statusDate; 
            } 
            set 
            {
                this.statusDate = value;
                onPropertyChanged("StatusDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contractStartDate")]
        public string ContractStartDate 
        { 
            get 
            {
                return this.contractStartDate; 
            } 
            set 
            {
                this.contractStartDate = value;
                onPropertyChanged("ContractStartDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contractEndDate")]
        public string ContractEndDate 
        { 
            get 
            {
                return this.contractEndDate; 
            } 
            set 
            {
                this.contractEndDate = value;
                onPropertyChanged("ContractEndDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("salesTeam")]
        public string SalesTeam 
        { 
            get 
            {
                return this.salesTeam; 
            } 
            set 
            {
                this.salesTeam = value;
                onPropertyChanged("SalesTeam");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("salesPerson")]
        public string SalesPerson 
        { 
            get 
            {
                return this.salesPerson; 
            } 
            set 
            {
                this.salesPerson = value;
                onPropertyChanged("SalesPerson");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customer")]
        public Models.Customer Customer 
        { 
            get 
            {
                return this.customer; 
            } 
            set 
            {
                this.customer = value;
                onPropertyChanged("Customer");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("product")]
        public Models.Product Product 
        { 
            get 
            {
                return this.product; 
            } 
            set 
            {
                this.product = value;
                onPropertyChanged("Product");
            }
        }
    }
} 