/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class CreateNewMandateCollectionSRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string objectId;
        private string mandateIdentification;
        private string collectionReference;
        private string forDate;
        private string requestedActionDate;
        private string amount;
        private string clientSegment;
        private string currency;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("objectId")]
        public string ObjectId 
        { 
            get 
            {
                return this.objectId; 
            } 
            set 
            {
                this.objectId = value;
                onPropertyChanged("ObjectId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mandateIdentification")]
        public string MandateIdentification 
        { 
            get 
            {
                return this.mandateIdentification; 
            } 
            set 
            {
                this.mandateIdentification = value;
                onPropertyChanged("MandateIdentification");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("collectionReference")]
        public string CollectionReference 
        { 
            get 
            {
                return this.collectionReference; 
            } 
            set 
            {
                this.collectionReference = value;
                onPropertyChanged("CollectionReference");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("forDate")]
        public string ForDate 
        { 
            get 
            {
                return this.forDate; 
            } 
            set 
            {
                this.forDate = value;
                onPropertyChanged("ForDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("requestedActionDate")]
        public string RequestedActionDate 
        { 
            get 
            {
                return this.requestedActionDate; 
            } 
            set 
            {
                this.requestedActionDate = value;
                onPropertyChanged("RequestedActionDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount")]
        public string Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientSegment")]
        public string ClientSegment 
        { 
            get 
            {
                return this.clientSegment; 
            } 
            set 
            {
                this.clientSegment = value;
                onPropertyChanged("ClientSegment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("currency")]
        public string Currency 
        { 
            get 
            {
                return this.currency; 
            } 
            set 
            {
                this.currency = value;
                onPropertyChanged("Currency");
            }
        }
    }
} 