/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class CreateNewNaedoCollectionSRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string objectId;
        private string creditorShortName;
        private string debtorName;
        private string debtorAccountNumber;
        private string debtorBranch;
        private string debtorBank;
        private string collectionReference;
        private string amount;
        private string requestedActionDate;
        private string mandateIdentification;
        private string trackingDays;
        private string debtorIdentificationType;
        private string debtorIdentification;
        private string debtorPhoneNumber;
        private string debtorEmail;
        private string debtorAccountType;
        private string forDate;
        private string preferredServiceType;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("objectId")]
        public string ObjectId 
        { 
            get 
            {
                return this.objectId; 
            } 
            set 
            {
                this.objectId = value;
                onPropertyChanged("ObjectId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("creditorShortName")]
        public string CreditorShortName 
        { 
            get 
            {
                return this.creditorShortName; 
            } 
            set 
            {
                this.creditorShortName = value;
                onPropertyChanged("CreditorShortName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorName")]
        public string DebtorName 
        { 
            get 
            {
                return this.debtorName; 
            } 
            set 
            {
                this.debtorName = value;
                onPropertyChanged("DebtorName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorAccountNumber")]
        public string DebtorAccountNumber 
        { 
            get 
            {
                return this.debtorAccountNumber; 
            } 
            set 
            {
                this.debtorAccountNumber = value;
                onPropertyChanged("DebtorAccountNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorBranch")]
        public string DebtorBranch 
        { 
            get 
            {
                return this.debtorBranch; 
            } 
            set 
            {
                this.debtorBranch = value;
                onPropertyChanged("DebtorBranch");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorBank")]
        public string DebtorBank 
        { 
            get 
            {
                return this.debtorBank; 
            } 
            set 
            {
                this.debtorBank = value;
                onPropertyChanged("DebtorBank");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("collectionReference")]
        public string CollectionReference 
        { 
            get 
            {
                return this.collectionReference; 
            } 
            set 
            {
                this.collectionReference = value;
                onPropertyChanged("CollectionReference");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount")]
        public string Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("requestedActionDate")]
        public string RequestedActionDate 
        { 
            get 
            {
                return this.requestedActionDate; 
            } 
            set 
            {
                this.requestedActionDate = value;
                onPropertyChanged("RequestedActionDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mandateIdentification")]
        public string MandateIdentification 
        { 
            get 
            {
                return this.mandateIdentification; 
            } 
            set 
            {
                this.mandateIdentification = value;
                onPropertyChanged("MandateIdentification");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trackingDays")]
        public string TrackingDays 
        { 
            get 
            {
                return this.trackingDays; 
            } 
            set 
            {
                this.trackingDays = value;
                onPropertyChanged("TrackingDays");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorIdentificationType")]
        public string DebtorIdentificationType 
        { 
            get 
            {
                return this.debtorIdentificationType; 
            } 
            set 
            {
                this.debtorIdentificationType = value;
                onPropertyChanged("DebtorIdentificationType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorIdentification")]
        public string DebtorIdentification 
        { 
            get 
            {
                return this.debtorIdentification; 
            } 
            set 
            {
                this.debtorIdentification = value;
                onPropertyChanged("DebtorIdentification");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorPhoneNumber")]
        public string DebtorPhoneNumber 
        { 
            get 
            {
                return this.debtorPhoneNumber; 
            } 
            set 
            {
                this.debtorPhoneNumber = value;
                onPropertyChanged("DebtorPhoneNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorEmail")]
        public string DebtorEmail 
        { 
            get 
            {
                return this.debtorEmail; 
            } 
            set 
            {
                this.debtorEmail = value;
                onPropertyChanged("DebtorEmail");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtorAccountType")]
        public string DebtorAccountType 
        { 
            get 
            {
                return this.debtorAccountType; 
            } 
            set 
            {
                this.debtorAccountType = value;
                onPropertyChanged("DebtorAccountType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("forDate")]
        public string ForDate 
        { 
            get 
            {
                return this.forDate; 
            } 
            set 
            {
                this.forDate = value;
                onPropertyChanged("ForDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("preferredServiceType")]
        public string PreferredServiceType 
        { 
            get 
            {
                return this.preferredServiceType; 
            } 
            set 
            {
                this.preferredServiceType = value;
                onPropertyChanged("PreferredServiceType");
            }
        }
    }
} 