/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class CreateNewPaymentSRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string objectId;
        private string bank;
        private string shortName;
        private string creditorName;
        private string creditorAccountNumber;
        private string creditorBranch;
        private string paymentReference;
        private string amount;
        private string paymentDate;
        private string instrument;
        private string creditorAccountType;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("objectId")]
        public string ObjectId 
        { 
            get 
            {
                return this.objectId; 
            } 
            set 
            {
                this.objectId = value;
                onPropertyChanged("ObjectId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bank")]
        public string Bank 
        { 
            get 
            {
                return this.bank; 
            } 
            set 
            {
                this.bank = value;
                onPropertyChanged("Bank");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("shortName")]
        public string ShortName 
        { 
            get 
            {
                return this.shortName; 
            } 
            set 
            {
                this.shortName = value;
                onPropertyChanged("ShortName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("creditorName")]
        public string CreditorName 
        { 
            get 
            {
                return this.creditorName; 
            } 
            set 
            {
                this.creditorName = value;
                onPropertyChanged("CreditorName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("creditorAccountNumber")]
        public string CreditorAccountNumber 
        { 
            get 
            {
                return this.creditorAccountNumber; 
            } 
            set 
            {
                this.creditorAccountNumber = value;
                onPropertyChanged("CreditorAccountNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("creditorBranch")]
        public string CreditorBranch 
        { 
            get 
            {
                return this.creditorBranch; 
            } 
            set 
            {
                this.creditorBranch = value;
                onPropertyChanged("CreditorBranch");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentReference")]
        public string PaymentReference 
        { 
            get 
            {
                return this.paymentReference; 
            } 
            set 
            {
                this.paymentReference = value;
                onPropertyChanged("PaymentReference");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount")]
        public string Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentDate")]
        public string PaymentDate 
        { 
            get 
            {
                return this.paymentDate; 
            } 
            set 
            {
                this.paymentDate = value;
                onPropertyChanged("PaymentDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("instrument")]
        public string Instrument 
        { 
            get 
            {
                return this.instrument; 
            } 
            set 
            {
                this.instrument = value;
                onPropertyChanged("Instrument");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("creditorAccountType")]
        public string CreditorAccountType 
        { 
            get 
            {
                return this.creditorAccountType; 
            } 
            set 
            {
                this.creditorAccountType = value;
                onPropertyChanged("CreditorAccountType");
            }
        }
    }
} 