/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class Creditor : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string accountNumber;
        private string accountName;
        private string branchCode;
        private string email;
        private string phoneNumber;
        private string schemeName;
        private string shortName;
        private string ultimateName;

        /// <summary>
        /// The creditor’s bank account number.
        /// </summary>
        [JsonProperty("accountNumber")]
        public string AccountNumber 
        { 
            get 
            {
                return this.accountNumber; 
            } 
            set 
            {
                this.accountNumber = value;
                onPropertyChanged("AccountNumber");
            }
        }

        /// <summary>
        /// The creditor’s account. name.
        /// </summary>
        [JsonProperty("accountName")]
        public string AccountName 
        { 
            get 
            {
                return this.accountName; 
            } 
            set 
            {
                this.accountName = value;
                onPropertyChanged("AccountName");
            }
        }

        /// <summary>
        /// The creditor’s 6 digit branch sort code.
        /// </summary>
        [JsonProperty("branchCode")]
        public string BranchCode 
        { 
            get 
            {
                return this.branchCode; 
            } 
            set 
            {
                this.branchCode = value;
                onPropertyChanged("BranchCode");
            }
        }

        /// <summary>
        /// The creditor’s email address.
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// The creditor’s phone number.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string PhoneNumber 
        { 
            get 
            {
                return this.phoneNumber; 
            } 
            set 
            {
                this.phoneNumber = value;
                onPropertyChanged("PhoneNumber");
            }
        }

        /// <summary>
        /// The creditor’s scheme name.
        /// </summary>
        [JsonProperty("schemeName")]
        public string SchemeName 
        { 
            get 
            {
                return this.schemeName; 
            } 
            set 
            {
                this.schemeName = value;
                onPropertyChanged("SchemeName");
            }
        }

        /// <summary>
        /// The ultimate creditor’s abbreviated short name.
        /// </summary>
        [JsonProperty("shortName")]
        public string ShortName 
        { 
            get 
            {
                return this.shortName; 
            } 
            set 
            {
                this.shortName = value;
                onPropertyChanged("ShortName");
            }
        }

        /// <summary>
        /// The ultimate creditor’s name.
        /// </summary>
        [JsonProperty("ultimateName")]
        public string UltimateName 
        { 
            get 
            {
                return this.ultimateName; 
            } 
            set 
            {
                this.ultimateName = value;
                onPropertyChanged("UltimateName");
            }
        }
    }
} 