/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class Debtor : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string accountNumber;
        private string accountType;
        private string branchCode;
        private string email;
        private string phoneNumber;
        private string identification;
        private string identificationType;

        /// <summary>
        /// The debtor’s name.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// The debtor’s bank account number.
        /// </summary>
        [JsonProperty("accountNumber")]
        public string AccountNumber 
        { 
            get 
            {
                return this.accountNumber; 
            } 
            set 
            {
                this.accountNumber = value;
                onPropertyChanged("AccountNumber");
            }
        }

        /// <summary>
        /// The debtor’s account type.
        /// </summary>
        [JsonProperty("accountType")]
        public string AccountType 
        { 
            get 
            {
                return this.accountType; 
            } 
            set 
            {
                this.accountType = value;
                onPropertyChanged("AccountType");
            }
        }

        /// <summary>
        /// The debtor’s 6 digit branch sort code.
        /// </summary>
        [JsonProperty("branchCode")]
        public string BranchCode 
        { 
            get 
            {
                return this.branchCode; 
            } 
            set 
            {
                this.branchCode = value;
                onPropertyChanged("BranchCode");
            }
        }

        /// <summary>
        /// The debtor’s email address.
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// The debtor’s mobile or landline number.
        /// </summary>
        [JsonProperty("phoneNumber")]
        public string PhoneNumber 
        { 
            get 
            {
                return this.phoneNumber; 
            } 
            set 
            {
                this.phoneNumber = value;
                onPropertyChanged("PhoneNumber");
            }
        }

        /// <summary>
        /// The debtor’s identification number.
        /// </summary>
        [JsonProperty("identification")]
        public string Identification 
        { 
            get 
            {
                return this.identification; 
            } 
            set 
            {
                this.identification = value;
                onPropertyChanged("Identification");
            }
        }

        /// <summary>
        /// The debtor’s identification type.
        /// </summary>
        [JsonProperty("identificationType")]
        public string IdentificationType 
        { 
            get 
            {
                return this.identificationType; 
            } 
            set 
            {
                this.identificationType = value;
                onPropertyChanged("IdentificationType");
            }
        }
    }
} 