/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class FintecAPISOwnUniqueAlgorithmToFICAYourClientsRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string idNumber;
        private string firstname;
        private string surname;
        private string enquiryReason;
        private string yourReference;
        private string street;
        private string suburb;
        private string city;
        private string province;
        private string poCode;
        private string dateRange;
        private string minimumMatch;
        private string secondname;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("idNumber")]
        public string IdNumber 
        { 
            get 
            {
                return this.idNumber; 
            } 
            set 
            {
                this.idNumber = value;
                onPropertyChanged("IdNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("firstname")]
        public string Firstname 
        { 
            get 
            {
                return this.firstname; 
            } 
            set 
            {
                this.firstname = value;
                onPropertyChanged("Firstname");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("surname")]
        public string Surname 
        { 
            get 
            {
                return this.surname; 
            } 
            set 
            {
                this.surname = value;
                onPropertyChanged("Surname");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("enquiryReason")]
        public string EnquiryReason 
        { 
            get 
            {
                return this.enquiryReason; 
            } 
            set 
            {
                this.enquiryReason = value;
                onPropertyChanged("EnquiryReason");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("yourReference")]
        public string YourReference 
        { 
            get 
            {
                return this.yourReference; 
            } 
            set 
            {
                this.yourReference = value;
                onPropertyChanged("YourReference");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("street")]
        public string Street 
        { 
            get 
            {
                return this.street; 
            } 
            set 
            {
                this.street = value;
                onPropertyChanged("Street");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("suburb")]
        public string Suburb 
        { 
            get 
            {
                return this.suburb; 
            } 
            set 
            {
                this.suburb = value;
                onPropertyChanged("Suburb");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("city")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("province")]
        public string Province 
        { 
            get 
            {
                return this.province; 
            } 
            set 
            {
                this.province = value;
                onPropertyChanged("Province");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("poCode")]
        public string PoCode 
        { 
            get 
            {
                return this.poCode; 
            } 
            set 
            {
                this.poCode = value;
                onPropertyChanged("PoCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("dateRange")]
        public string DateRange 
        { 
            get 
            {
                return this.dateRange; 
            } 
            set 
            {
                this.dateRange = value;
                onPropertyChanged("DateRange");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("minimumMatch")]
        public string MinimumMatch 
        { 
            get 
            {
                return this.minimumMatch; 
            } 
            set 
            {
                this.minimumMatch = value;
                onPropertyChanged("MinimumMatch");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("secondname")]
        public string Secondname 
        { 
            get 
            {
                return this.secondname; 
            } 
            set 
            {
                this.secondname = value;
                onPropertyChanged("Secondname");
            }
        }
    }
} 