/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class GetTheCompanyCIPCSearchResultsRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string companyDetailsyourReference;
        private string companyDetailsreg1;
        private string companyDetailsreg2;
        private string companyDetailsreg3;
        private string companyDetailsbusinessName;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("company_detailsyourReference")]
        public string CompanyDetailsyourReference 
        { 
            get 
            {
                return this.companyDetailsyourReference; 
            } 
            set 
            {
                this.companyDetailsyourReference = value;
                onPropertyChanged("CompanyDetailsyourReference");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("company_detailsreg1")]
        public string CompanyDetailsreg1 
        { 
            get 
            {
                return this.companyDetailsreg1; 
            } 
            set 
            {
                this.companyDetailsreg1 = value;
                onPropertyChanged("CompanyDetailsreg1");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("company_detailsreg2")]
        public string CompanyDetailsreg2 
        { 
            get 
            {
                return this.companyDetailsreg2; 
            } 
            set 
            {
                this.companyDetailsreg2 = value;
                onPropertyChanged("CompanyDetailsreg2");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("company_detailsreg3")]
        public string CompanyDetailsreg3 
        { 
            get 
            {
                return this.companyDetailsreg3; 
            } 
            set 
            {
                this.companyDetailsreg3 = value;
                onPropertyChanged("CompanyDetailsreg3");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("company_detailsbusinessName")]
        public string CompanyDetailsbusinessName 
        { 
            get 
            {
                return this.companyDetailsbusinessName; 
            } 
            set 
            {
                this.companyDetailsbusinessName = value;
                onPropertyChanged("CompanyDetailsbusinessName");
            }
        }
    }
} 