/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class Identification : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string collectionIdentification;
        private string clientSegment;
        private string requestedActionDate;
        private string forDate;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("collectionIdentification")]
        public string CollectionIdentification 
        { 
            get 
            {
                return this.collectionIdentification; 
            } 
            set 
            {
                this.collectionIdentification = value;
                onPropertyChanged("CollectionIdentification");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientSegment")]
        public string ClientSegment 
        { 
            get 
            {
                return this.clientSegment; 
            } 
            set 
            {
                this.clientSegment = value;
                onPropertyChanged("ClientSegment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("requestedActionDate")]
        public string RequestedActionDate 
        { 
            get 
            {
                return this.requestedActionDate; 
            } 
            set 
            {
                this.requestedActionDate = value;
                onPropertyChanged("RequestedActionDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("forDate")]
        public string ForDate 
        { 
            get 
            {
                return this.forDate; 
            } 
            set 
            {
                this.forDate = value;
                onPropertyChanged("ForDate");
            }
        }
    }
} 