/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class Mandate : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string mandateIdentification;
        private string amendmentReasonCode;
        private string cancellationReasonCode;
        private string mandateStatus;
        private string authenticationStatus;
        private string createdAt;
        private string modifiedAt;
        private double adjustmentAmount;
        private string adjustmentCategory;
        private double adjustmentRate;
        private string authenticationCode;
        private string authenticationDate;
        private string authenticationInstrument;
        private string authenticationType;
        private string clientContractReference;
        private string clientRequestReference;
        private string collectionFrequency;
        private string collectionDay;
        private string collectionType;
        private string currency;
        private bool dateAdjustmentAllowed;
        private string debitValueType;
        private string entryClass;
        private string firstCollectionIdentifier;
        private string firstCollectionDate;
        private double firstCollectionAmount;
        private string firstCollectionCurrency;
        private string initiationDate;
        private double instalmentAmount;
        private string instalmentOccurrence;
        private string debiCheckAuthKey;
        private string clientSegment;
        private bool trackingAllowed;
        private int trackingDays;
        private bool useAmountAdjustment;
        private bool useRateAdjustment;
        private string releaseDate;
        private string maxCollectionCurrency;
        private string idVerificationStatus;
        private string bankAccountVerificationStatus;
        private double maxCollectionAmount;
        private Models.Debtor debtor;
        private Models.Creditor creditor;
        private List<Models.AdditionalDatum> additionalData;
        private Models.OptiCollectMandate optiCollectMandate;

        /// <summary>
        /// The unique mandate identifier assigned by the creditor.
        /// </summary>
        [JsonProperty("mandateIdentification")]
        public string MandateIdentification 
        { 
            get 
            {
                return this.mandateIdentification; 
            } 
            set 
            {
                this.mandateIdentification = value;
                onPropertyChanged("MandateIdentification");
            }
        }

        /// <summary>
        /// The reason code.
        /// </summary>
        [JsonProperty("amendmentReasonCode")]
        public string AmendmentReasonCode 
        { 
            get 
            {
                return this.amendmentReasonCode; 
            } 
            set 
            {
                this.amendmentReasonCode = value;
                onPropertyChanged("AmendmentReasonCode");
            }
        }

        /// <summary>
        /// The reason code.
        /// </summary>
        [JsonProperty("cancellationReasonCode")]
        public string CancellationReasonCode 
        { 
            get 
            {
                return this.cancellationReasonCode; 
            } 
            set 
            {
                this.cancellationReasonCode = value;
                onPropertyChanged("CancellationReasonCode");
            }
        }

        /// <summary>
        /// The status of the mandate.
        /// </summary>
        [JsonProperty("mandateStatus")]
        public string MandateStatus 
        { 
            get 
            {
                return this.mandateStatus; 
            } 
            set 
            {
                this.mandateStatus = value;
                onPropertyChanged("MandateStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("authenticationStatus")]
        public string AuthenticationStatus 
        { 
            get 
            {
                return this.authenticationStatus; 
            } 
            set 
            {
                this.authenticationStatus = value;
                onPropertyChanged("AuthenticationStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createdAt")]
        public string CreatedAt 
        { 
            get 
            {
                return this.createdAt; 
            } 
            set 
            {
                this.createdAt = value;
                onPropertyChanged("CreatedAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("modifiedAt")]
        public string ModifiedAt 
        { 
            get 
            {
                return this.modifiedAt; 
            } 
            set 
            {
                this.modifiedAt = value;
                onPropertyChanged("ModifiedAt");
            }
        }

        /// <summary>
        /// The amount by which the installment and maximum collection amounts can be adjusted.
        /// </summary>
        [JsonProperty("adjustmentAmount")]
        public double AdjustmentAmount 
        { 
            get 
            {
                return this.adjustmentAmount; 
            } 
            set 
            {
                this.adjustmentAmount = value;
                onPropertyChanged("AdjustmentAmount");
            }
        }

        /// <summary>
        /// The category, referring to the time period to adjust installment and max collection amounts.
        /// </summary>
        [JsonProperty("adjustmentCategory")]
        public string AdjustmentCategory 
        { 
            get 
            {
                return this.adjustmentCategory; 
            } 
            set 
            {
                this.adjustmentCategory = value;
                onPropertyChanged("AdjustmentCategory");
            }
        }

        /// <summary>
        /// The rate by which the installment and the maximum collection amounts can be adjusted.
        /// </summary>
        [JsonProperty("adjustmentRate")]
        public double AdjustmentRate 
        { 
            get 
            {
                return this.adjustmentRate; 
            } 
            set 
            {
                this.adjustmentRate = value;
                onPropertyChanged("AdjustmentRate");
            }
        }

        /// <summary>
        /// The message authentication code (MAC).
        /// </summary>
        [JsonProperty("authenticationCode")]
        public string AuthenticationCode 
        { 
            get 
            {
                return this.authenticationCode; 
            } 
            set 
            {
                this.authenticationCode = value;
                onPropertyChanged("AuthenticationCode");
            }
        }

        /// <summary>
        /// The date of authentication.
        /// </summary>
        [JsonProperty("authenticationDate")]
        public string AuthenticationDate 
        { 
            get 
            {
                return this.authenticationDate; 
            } 
            set 
            {
                this.authenticationDate = value;
                onPropertyChanged("AuthenticationDate");
            }
        }

        /// <summary>
        /// The authentication method.
        /// </summary>
        [JsonProperty("authenticationInstrument")]
        public string AuthenticationInstrument 
        { 
            get 
            {
                return this.authenticationInstrument; 
            } 
            set 
            {
                this.authenticationInstrument = value;
                onPropertyChanged("AuthenticationInstrument");
            }
        }

        /// <summary>
        /// The transaction type that will be used for authentication.
        /// </summary>
        [JsonProperty("authenticationType")]
        public string AuthenticationType 
        { 
            get 
            {
                return this.authenticationType; 
            } 
            set 
            {
                this.authenticationType = value;
                onPropertyChanged("AuthenticationType");
            }
        }

        /// <summary>
        /// The debtor’s contract reference.
        /// </summary>
        [JsonProperty("clientContractReference")]
        public string ClientContractReference 
        { 
            get 
            {
                return this.clientContractReference; 
            } 
            set 
            {
                this.clientContractReference = value;
                onPropertyChanged("ClientContractReference");
            }
        }

        /// <summary>
        /// The unique reference to the client request.
        /// </summary>
        [JsonProperty("clientRequestReference")]
        public string ClientRequestReference 
        { 
            get 
            {
                return this.clientRequestReference; 
            } 
            set 
            {
                this.clientRequestReference = value;
                onPropertyChanged("ClientRequestReference");
            }
        }

        /// <summary>
        /// The regularity of the collection.
        /// </summary>
        [JsonProperty("collectionFrequency")]
        public string CollectionFrequency 
        { 
            get 
            {
                return this.collectionFrequency; 
            } 
            set 
            {
                this.collectionFrequency = value;
                onPropertyChanged("CollectionFrequency");
            }
        }

        /// <summary>
        /// The numeric representation of the collection day.
        /// </summary>
        [JsonProperty("collectionDay")]
        public string CollectionDay 
        { 
            get 
            {
                return this.collectionDay; 
            } 
            set 
            {
                this.collectionDay = value;
                onPropertyChanged("CollectionDay");
            }
        }

        /// <summary>
        /// The collection authentication type.
        /// </summary>
        [JsonProperty("collectionType")]
        public string CollectionType 
        { 
            get 
            {
                return this.collectionType; 
            } 
            set 
            {
                this.collectionType = value;
                onPropertyChanged("CollectionType");
            }
        }

        /// <summary>
        /// The collection currency.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency 
        { 
            get 
            {
                return this.currency; 
            } 
            set 
            {
                this.currency = value;
                onPropertyChanged("Currency");
            }
        }

        /// <summary>
        /// The permission to adjust dates flag.
        /// </summary>
        [JsonProperty("dateAdjustmentAllowed")]
        public bool DateAdjustmentAllowed 
        { 
            get 
            {
                return this.dateAdjustmentAllowed; 
            } 
            set 
            {
                this.dateAdjustmentAllowed = value;
                onPropertyChanged("DateAdjustmentAllowed");
            }
        }

        /// <summary>
        /// The mandate value type
        /// </summary>
        [JsonProperty("debitValueType")]
        public string DebitValueType 
        { 
            get 
            {
                return this.debitValueType; 
            } 
            set 
            {
                this.debitValueType = value;
                onPropertyChanged("DebitValueType");
            }
        }

        /// <summary>
        /// The type of debit as determined by the creditor.
        /// </summary>
        [JsonProperty("entryClass")]
        public string EntryClass 
        { 
            get 
            {
                return this.entryClass; 
            } 
            set 
            {
                this.entryClass = value;
                onPropertyChanged("EntryClass");
            }
        }

        /// <summary>
        /// The unique first collection reference.
        /// </summary>
        [JsonProperty("firstCollectionIdentifier")]
        public string FirstCollectionIdentifier 
        { 
            get 
            {
                return this.firstCollectionIdentifier; 
            } 
            set 
            {
                this.firstCollectionIdentifier = value;
                onPropertyChanged("FirstCollectionIdentifier");
            }
        }

        /// <summary>
        /// The date on which the first collection will occur.
        /// </summary>
        [JsonProperty("firstCollectionDate")]
        public string FirstCollectionDate 
        { 
            get 
            {
                return this.firstCollectionDate; 
            } 
            set 
            {
                this.firstCollectionDate = value;
                onPropertyChanged("FirstCollectionDate");
            }
        }

        /// <summary>
        /// The first collection amount.
        /// </summary>
        [JsonProperty("firstCollectionAmount")]
        public double FirstCollectionAmount 
        { 
            get 
            {
                return this.firstCollectionAmount; 
            } 
            set 
            {
                this.firstCollectionAmount = value;
                onPropertyChanged("FirstCollectionAmount");
            }
        }

        /// <summary>
        /// The first collection currency.
        /// </summary>
        [JsonProperty("firstCollectionCurrency")]
        public string FirstCollectionCurrency 
        { 
            get 
            {
                return this.firstCollectionCurrency; 
            } 
            set 
            {
                this.firstCollectionCurrency = value;
                onPropertyChanged("FirstCollectionCurrency");
            }
        }

        /// <summary>
        /// The date from which collections on the mandate contract can then be collected on.
        /// </summary>
        [JsonProperty("initiationDate")]
        public string InitiationDate 
        { 
            get 
            {
                return this.initiationDate; 
            } 
            set 
            {
                this.initiationDate = value;
                onPropertyChanged("InitiationDate");
            }
        }

        /// <summary>
        /// The regular collection amount.
        /// </summary>
        [JsonProperty("instalmentAmount")]
        public double InstalmentAmount 
        { 
            get 
            {
                return this.instalmentAmount; 
            } 
            set 
            {
                this.instalmentAmount = value;
                onPropertyChanged("InstalmentAmount");
            }
        }

        /// <summary>
        /// The occurance of the installment.
        /// </summary>
        [JsonProperty("instalmentOccurrence")]
        public string InstalmentOccurrence 
        { 
            get 
            {
                return this.instalmentOccurrence; 
            } 
            set 
            {
                this.instalmentOccurrence = value;
                onPropertyChanged("InstalmentOccurrence");
            }
        }

        /// <summary>
        /// The unique key as received after the mandate has been authenticated.
        /// </summary>
        [JsonProperty("debiCheckAuthKey")]
        public string DebiCheckAuthKey 
        { 
            get 
            {
                return this.debiCheckAuthKey; 
            } 
            set 
            {
                this.debiCheckAuthKey = value;
                onPropertyChanged("DebiCheckAuthKey");
            }
        }

        /// <summary>
        /// The client segment the collection falls into.
        /// </summary>
        [JsonProperty("clientSegment")]
        public string ClientSegment 
        { 
            get 
            {
                return this.clientSegment; 
            } 
            set 
            {
                this.clientSegment = value;
                onPropertyChanged("ClientSegment");
            }
        }

        /// <summary>
        /// The permission to track collections flag.
        /// </summary>
        [JsonProperty("trackingAllowed")]
        public bool TrackingAllowed 
        { 
            get 
            {
                return this.trackingAllowed; 
            } 
            set 
            {
                this.trackingAllowed = value;
                onPropertyChanged("TrackingAllowed");
            }
        }

        /// <summary>
        /// The number of days to track for.
        /// </summary>
        [JsonProperty("trackingDays")]
        public int TrackingDays 
        { 
            get 
            {
                return this.trackingDays; 
            } 
            set 
            {
                this.trackingDays = value;
                onPropertyChanged("TrackingDays");
            }
        }

        /// <summary>
        /// The permission to use the amount adjustment flag.
        /// </summary>
        [JsonProperty("useAmountAdjustment")]
        public bool UseAmountAdjustment 
        { 
            get 
            {
                return this.useAmountAdjustment; 
            } 
            set 
            {
                this.useAmountAdjustment = value;
                onPropertyChanged("UseAmountAdjustment");
            }
        }

        /// <summary>
        /// The permission to use the rate adjustment flag.
        /// </summary>
        [JsonProperty("useRateAdjustment")]
        public bool UseRateAdjustment 
        { 
            get 
            {
                return this.useRateAdjustment; 
            } 
            set 
            {
                this.useRateAdjustment = value;
                onPropertyChanged("UseRateAdjustment");
            }
        }

        /// <summary>
        /// The date on which the mandate may be released.
        /// </summary>
        [JsonProperty("releaseDate")]
        public string ReleaseDate 
        { 
            get 
            {
                return this.releaseDate; 
            } 
            set 
            {
                this.releaseDate = value;
                onPropertyChanged("ReleaseDate");
            }
        }

        /// <summary>
        /// The maximum collection currency.
        /// </summary>
        [JsonProperty("maxCollectionCurrency")]
        public string MaxCollectionCurrency 
        { 
            get 
            {
                return this.maxCollectionCurrency; 
            } 
            set 
            {
                this.maxCollectionCurrency = value;
                onPropertyChanged("MaxCollectionCurrency");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("idVerificationStatus")]
        public string IdVerificationStatus 
        { 
            get 
            {
                return this.idVerificationStatus; 
            } 
            set 
            {
                this.idVerificationStatus = value;
                onPropertyChanged("IdVerificationStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankAccountVerificationStatus")]
        public string BankAccountVerificationStatus 
        { 
            get 
            {
                return this.bankAccountVerificationStatus; 
            } 
            set 
            {
                this.bankAccountVerificationStatus = value;
                onPropertyChanged("BankAccountVerificationStatus");
            }
        }

        /// <summary>
        /// The maximum collection amount that the creditor is allowed to collect per debit payment.
        /// </summary>
        [JsonProperty("maxCollectionAmount")]
        public double MaxCollectionAmount 
        { 
            get 
            {
                return this.maxCollectionAmount; 
            } 
            set 
            {
                this.maxCollectionAmount = value;
                onPropertyChanged("MaxCollectionAmount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("debtor")]
        public Models.Debtor Debtor 
        { 
            get 
            {
                return this.debtor; 
            } 
            set 
            {
                this.debtor = value;
                onPropertyChanged("Debtor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("creditor")]
        public Models.Creditor Creditor 
        { 
            get 
            {
                return this.creditor; 
            } 
            set 
            {
                this.creditor = value;
                onPropertyChanged("Creditor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("additionalData")]
        public List<Models.AdditionalDatum> AdditionalData 
        { 
            get 
            {
                return this.additionalData; 
            } 
            set 
            {
                this.additionalData = value;
                onPropertyChanged("AdditionalData");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("optiCollectMandate")]
        public Models.OptiCollectMandate OptiCollectMandate 
        { 
            get 
            {
                return this.optiCollectMandate; 
            } 
            set 
            {
                this.optiCollectMandate = value;
                onPropertyChanged("OptiCollectMandate");
            }
        }
    }
} 