/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class Mandate1 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string mandateIdentification;
        private string mandateStatus;
        private string clientContractReference;
        private string initiationDate;
        private string releaseDate;
        private double instalmentAmount;
        private string collectionDay;
        private string instalmentOccurrence;
        private string collectionFrequency;
        private bool isDebiCheck;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mandateIdentification")]
        public string MandateIdentification 
        { 
            get 
            {
                return this.mandateIdentification; 
            } 
            set 
            {
                this.mandateIdentification = value;
                onPropertyChanged("MandateIdentification");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mandateStatus")]
        public string MandateStatus 
        { 
            get 
            {
                return this.mandateStatus; 
            } 
            set 
            {
                this.mandateStatus = value;
                onPropertyChanged("MandateStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clientContractReference")]
        public string ClientContractReference 
        { 
            get 
            {
                return this.clientContractReference; 
            } 
            set 
            {
                this.clientContractReference = value;
                onPropertyChanged("ClientContractReference");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("initiationDate")]
        public string InitiationDate 
        { 
            get 
            {
                return this.initiationDate; 
            } 
            set 
            {
                this.initiationDate = value;
                onPropertyChanged("InitiationDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("releaseDate")]
        public string ReleaseDate 
        { 
            get 
            {
                return this.releaseDate; 
            } 
            set 
            {
                this.releaseDate = value;
                onPropertyChanged("ReleaseDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("instalmentAmount")]
        public double InstalmentAmount 
        { 
            get 
            {
                return this.instalmentAmount; 
            } 
            set 
            {
                this.instalmentAmount = value;
                onPropertyChanged("InstalmentAmount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("collectionDay")]
        public string CollectionDay 
        { 
            get 
            {
                return this.collectionDay; 
            } 
            set 
            {
                this.collectionDay = value;
                onPropertyChanged("CollectionDay");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("instalmentOccurrence")]
        public string InstalmentOccurrence 
        { 
            get 
            {
                return this.instalmentOccurrence; 
            } 
            set 
            {
                this.instalmentOccurrence = value;
                onPropertyChanged("InstalmentOccurrence");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("collectionFrequency")]
        public string CollectionFrequency 
        { 
            get 
            {
                return this.collectionFrequency; 
            } 
            set 
            {
                this.collectionFrequency = value;
                onPropertyChanged("CollectionFrequency");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isDebiCheck")]
        public bool IsDebiCheck 
        { 
            get 
            {
                return this.isDebiCheck; 
            } 
            set 
            {
                this.isDebiCheck = value;
                onPropertyChanged("IsDebiCheck");
            }
        }
    }
} 