/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class Product : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string productCode;
        private string productDescription;
        private string businessLine;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("productCode")]
        public string ProductCode 
        { 
            get 
            {
                return this.productCode; 
            } 
            set 
            {
                this.productCode = value;
                onPropertyChanged("ProductCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("productDescription")]
        public string ProductDescription 
        { 
            get 
            {
                return this.productDescription; 
            } 
            set 
            {
                this.productDescription = value;
                onPropertyChanged("ProductDescription");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("businessLine")]
        public string BusinessLine 
        { 
            get 
            {
                return this.businessLine; 
            } 
            set 
            {
                this.businessLine = value;
                onPropertyChanged("BusinessLine");
            }
        }
    }
} 