/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class ResponseSuccessfulCIPCMatchResultIsPositive : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.BusinessInformation businessInformation;
        private List<Models.AuditorInformation> auditorInformation;
        private List<Models.DirectorInformation> directorInformation;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("businessInformation")]
        public Models.BusinessInformation BusinessInformation 
        { 
            get 
            {
                return this.businessInformation; 
            } 
            set 
            {
                this.businessInformation = value;
                onPropertyChanged("BusinessInformation");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("auditorInformation")]
        public List<Models.AuditorInformation> AuditorInformation 
        { 
            get 
            {
                return this.auditorInformation; 
            } 
            set 
            {
                this.auditorInformation = value;
                onPropertyChanged("AuditorInformation");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("directorInformation")]
        public List<Models.DirectorInformation> DirectorInformation 
        { 
            get 
            {
                return this.directorInformation; 
            } 
            set 
            {
                this.directorInformation = value;
                onPropertyChanged("DirectorInformation");
            }
        }
    }
} 