/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class SendALocationThroughWhatsAppToAMobileNumber : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string to = "+27827265991";
        private string body = "Hello World!";
        private Models.LocationAttributes locationAttributes;

        /// <summary>
        /// The mobile number. Must be in the specified format.
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// The message body
        /// </summary>
        [JsonProperty("body")]
        public string Body 
        { 
            get 
            {
                return this.body; 
            } 
            set 
            {
                this.body = value;
                onPropertyChanged("Body");
            }
        }

        /// <summary>
        /// The location
        /// </summary>
        [JsonProperty("locationAttributes")]
        public Models.LocationAttributes LocationAttributes 
        { 
            get 
            {
                return this.locationAttributes; 
            } 
            set 
            {
                this.locationAttributes = value;
                onPropertyChanged("LocationAttributes");
            }
        }
    }
} 