/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class SendATemplatedWhatsAppMessageToAMobileNumberRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string to;
        private List<Models.MessageField> messageFields;
        private string templateName;
        private string templateId;

        /// <summary>
        /// The mobile number. Must be in the specified format.
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// The corresponding field entries of each template.
        /// </summary>
        [JsonProperty("messageFields")]
        public List<Models.MessageField> MessageFields 
        { 
            get 
            {
                return this.messageFields; 
            } 
            set 
            {
                this.messageFields = value;
                onPropertyChanged("MessageFields");
            }
        }

        /// <summary>
        /// The name of the template to be sent.
        /// </summary>
        [JsonProperty("templateName")]
        public string TemplateName 
        { 
            get 
            {
                return this.templateName; 
            } 
            set 
            {
                this.templateName = value;
                onPropertyChanged("TemplateName");
            }
        }

        /// <summary>
        /// The Id of the template to be sent.
        /// </summary>
        [JsonProperty("templateId")]
        public string TemplateId 
        { 
            get 
            {
                return this.templateId; 
            } 
            set 
            {
                this.templateId = value;
                onPropertyChanged("TemplateId");
            }
        }
    }
} 