/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class SendADocumentThroughWhatsAppToAMobileNumberRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string to = "+27827265991";
        private string text = "Hello World!";
        private string fileUrl;

        /// <summary>
        /// The mobile number. Must be in the specified format.
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// The content of the message.
        /// </summary>
        [JsonProperty("text")]
        public string Text 
        { 
            get 
            {
                return this.text; 
            } 
            set 
            {
                this.text = value;
                onPropertyChanged("Text");
            }
        }

        /// <summary>
        /// The url pointing to the document’s destination.
        /// </summary>
        [JsonProperty("fileUrl")]
        public string FileUrl 
        { 
            get 
            {
                return this.fileUrl; 
            } 
            set 
            {
                this.fileUrl = value;
                onPropertyChanged("FileUrl");
            }
        }
    }
} 