/*
 * BankTechAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities;


namespace BankTechAPI.Standard.Models
{
    public class VerifyAMandatesDebtorBankAccountRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string verificationType;
        private string companyRegNo;
        private string companyName;
        private int idNumber;
        private string initials;
        private string surname;
        private string bankName;
        private string accNumber;
        private string accType;
        private string yourReference;

        /// <summary>
        /// The type of Verification, can be either Company or Individual
        /// </summary>
        [JsonProperty("verificationType")]
        public string VerificationType 
        { 
            get 
            {
                return this.verificationType; 
            } 
            set 
            {
                this.verificationType = value;
                onPropertyChanged("VerificationType");
            }
        }

        /// <summary>
        /// if Verification Type is Company this is the Company registration number in the following format xxxx/xxxxxx/xx
        /// </summary>
        [JsonProperty("companyRegNo")]
        public string CompanyRegNo 
        { 
            get 
            {
                return this.companyRegNo; 
            } 
            set 
            {
                this.companyRegNo = value;
                onPropertyChanged("CompanyRegNo");
            }
        }

        /// <summary>
        /// if Verification Type is Company, this will be the Company Name
        /// </summary>
        [JsonProperty("companyName")]
        public string CompanyName 
        { 
            get 
            {
                return this.companyName; 
            } 
            set 
            {
                this.companyName = value;
                onPropertyChanged("CompanyName");
            }
        }

        /// <summary>
        /// if Verification Type is Individual, this will be the persons ID Number
        /// </summary>
        [JsonProperty("idNumber")]
        public int IdNumber 
        { 
            get 
            {
                return this.idNumber; 
            } 
            set 
            {
                this.idNumber = value;
                onPropertyChanged("IdNumber");
            }
        }

        /// <summary>
        /// if Verification Type is Individual, this will be the initials of person
        /// </summary>
        [JsonProperty("initials")]
        public string Initials 
        { 
            get 
            {
                return this.initials; 
            } 
            set 
            {
                this.initials = value;
                onPropertyChanged("Initials");
            }
        }

        /// <summary>
        /// if Verification Type is Individual, this will be the initials of person
        /// </summary>
        [JsonProperty("surname")]
        public string Surname 
        { 
            get 
            {
                return this.surname; 
            } 
            set 
            {
                this.surname = value;
                onPropertyChanged("Surname");
            }
        }

        /// <summary>
        /// The name of bank can be any of the following - (ABSA; FNB; STANDARDBANK, NEDBANK, CAPITEC)
        /// </summary>
        [JsonProperty("bankName")]
        public string BankName 
        { 
            get 
            {
                return this.bankName; 
            } 
            set 
            {
                this.bankName = value;
                onPropertyChanged("BankName");
            }
        }

        /// <summary>
        /// The bank account number of account holder
        /// </summary>
        [JsonProperty("accNumber")]
        public string AccNumber 
        { 
            get 
            {
                return this.accNumber; 
            } 
            set 
            {
                this.accNumber = value;
                onPropertyChanged("AccNumber");
            }
        }

        /// <summary>
        /// The bank account type of account holder (CURRENTCHEQUEACCOUNT,SAVINGSACCOUNT,TRANSMISSION,BOND)
        /// </summary>
        [JsonProperty("accType")]
        public string AccType 
        { 
            get 
            {
                return this.accType; 
            } 
            set 
            {
                this.accType = value;
                onPropertyChanged("AccType");
            }
        }

        /// <summary>
        /// Your Search Reference - Internal use
        /// </summary>
        [JsonProperty("yourReference")]
        public string YourReference 
        { 
            get 
            {
                return this.yourReference; 
            } 
            set 
            {
                this.yourReference = value;
                onPropertyChanged("YourReference");
            }
        }
    }
} 