/*
 * BankTechAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Utilities; 
using BankTechAPI.Standard.Http.Client;
using BankTechAPI.Standard.Http.Response;
using BankTechAPI.Tests.Helpers;
using NUnit.Framework;
using BankTechAPI.Standard;
using BankTechAPI.Standard.Controllers;
using BankTechAPI.Standard.Exceptions;

namespace BankTechAPI.Tests
{
    [TestFixture]
    public class CommunicationControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static CommunicationController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Communication;
        }

    }
}